set exrc
set relativenumber
set number
set nohlsearch
set noerrorbells
set hidden
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set nowrap
set undodir=~/.vim/undodir
set undofile
set incsearch
set scrolloff=12
