#!/bin/sh
###########
# aliases #
###########

alias \
	la="ls -lha"                 \
	c="clear"                    \
	df="df -h"                   \
	q="exit"                     \
	py="python"                  \
	gcl="git clone"              \
	md="mkdir"                   \
	tl="tldr"                    \
	dd="dd status=progress"      \
	tmux="tmux -2 -u"

if command -v exa &> /dev/null; then
    alias \
		ls="exa"                 \
		tree="exa --tree"
fi
