#!/bin/sh
###########
# aliases #
###########

alias \
	la="ls -lha"                 \
	c="clear"                    \
	df="df -h"                   \
	q="exit"                     \
	py="python"                  \
	gcl="git clone"              \
	md="mkdir"                   \
	tl="tldr"                    \
	dd="dd status=progress"      \

alias\
	doas="doas "                  \
