require("core/keymap")
require("plugins/plugins")
require("plugins/lsp")
require("plugins/theme")
require("plugins/noice")
require("plugins/telescope")
require("plugins/keymap")
require("core/interface")
